columns:
  Location: string
  Price: float
  Type: string
  No_Beds: int
  No_Baths: int
  Area: float
  Latitude: float
  Longitude: float
  Region: string
  Sub_region: string

target_column: Price

# Used by Data Transformation to apply specific scaling/encoding
NUMERICAL_COLUMNS:
  - No_Beds
  - No_Baths
  - Area
  - Latitude
  - Longitude

CATEGORICAL_COLUMNS:
  - Location
  - Type
  - Region
  - Sub_region
